# Generated by Django 5.1.5 on 2025-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_area', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=396)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
